#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : libspelling
Version  : 0.4.6
Release  : 5
URL      : https://gitlab.gnome.org/GNOME/libspelling/-/archive/0.4.6/libspelling-0.4.6.tar.gz
Source0  : https://gitlab.gnome.org/GNOME/libspelling/-/archive/0.4.6/libspelling-0.4.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: libspelling-data = %{version}-%{release}
Requires: libspelling-lib = %{version}-%{release}
Requires: libspelling-license = %{version}-%{release}
Requires: libspelling-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gi-docgen
BuildRequires : pkgconfig(enchant-2)
BuildRequires : pkgconfig(gtksourceview-5)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libspelling
A spellcheck library for GTK 4.
This library is heavily based upon GNOME Text Editor and GNOME Builder's
spellcheck implementation. However, it is licensed LGPLv2.1+.

%package data
Summary: data components for the libspelling package.
Group: Data

%description data
data components for the libspelling package.


%package dev
Summary: dev components for the libspelling package.
Group: Development
Requires: libspelling-lib = %{version}-%{release}
Requires: libspelling-data = %{version}-%{release}
Provides: libspelling-devel = %{version}-%{release}
Requires: libspelling = %{version}-%{release}

%description dev
dev components for the libspelling package.


%package doc
Summary: doc components for the libspelling package.
Group: Documentation

%description doc
doc components for the libspelling package.


%package lib
Summary: lib components for the libspelling package.
Group: Libraries
Requires: libspelling-data = %{version}-%{release}
Requires: libspelling-license = %{version}-%{release}

%description lib
lib components for the libspelling package.


%package license
Summary: license components for the libspelling package.
Group: Default

%description license
license components for the libspelling package.


%package locales
Summary: locales components for the libspelling package.
Group: Default

%description locales
locales components for the libspelling package.


%prep
%setup -q -n libspelling-0.4.6
cd %{_builddir}/libspelling-0.4.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738080287
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dsysprof=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libspelling
cp %{_builddir}/libspelling-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libspelling/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libspelling

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Spelling-1.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/libspelling-1.deps
/usr/share/vala/vapi/libspelling-1.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libspelling-1/libspelling.h
/usr/include/libspelling-1/spelling-checker.h
/usr/include/libspelling-1/spelling-dictionary.h
/usr/include/libspelling-1/spelling-init.h
/usr/include/libspelling-1/spelling-language.h
/usr/include/libspelling-1/spelling-provider.h
/usr/include/libspelling-1/spelling-text-buffer-adapter.h
/usr/include/libspelling-1/spelling-types.h
/usr/include/libspelling-1/spelling-version-macros.h
/usr/include/libspelling-1/spelling-version.h
/usr/lib64/libspelling-1.so
/usr/lib64/pkgconfig/libspelling-1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libspelling-1/RedHatDisplay-Black.woff
/usr/share/doc/libspelling-1/RedHatDisplay-Black.woff2
/usr/share/doc/libspelling-1/RedHatDisplay-BlackItalic.woff
/usr/share/doc/libspelling-1/RedHatDisplay-BlackItalic.woff2
/usr/share/doc/libspelling-1/RedHatDisplay-Bold.woff
/usr/share/doc/libspelling-1/RedHatDisplay-Bold.woff2
/usr/share/doc/libspelling-1/RedHatDisplay-BoldItalic.woff
/usr/share/doc/libspelling-1/RedHatDisplay-BoldItalic.woff2
/usr/share/doc/libspelling-1/RedHatDisplay-Italic.woff
/usr/share/doc/libspelling-1/RedHatDisplay-Italic.woff2
/usr/share/doc/libspelling-1/RedHatDisplay-Medium.woff
/usr/share/doc/libspelling-1/RedHatDisplay-Medium.woff2
/usr/share/doc/libspelling-1/RedHatDisplay-MediumItalic.woff
/usr/share/doc/libspelling-1/RedHatDisplay-MediumItalic.woff2
/usr/share/doc/libspelling-1/RedHatDisplay-Regular.woff
/usr/share/doc/libspelling-1/RedHatDisplay-Regular.woff2
/usr/share/doc/libspelling-1/RedHatText-Bold.woff
/usr/share/doc/libspelling-1/RedHatText-Bold.woff2
/usr/share/doc/libspelling-1/RedHatText-BoldItalic.woff
/usr/share/doc/libspelling-1/RedHatText-BoldItalic.woff2
/usr/share/doc/libspelling-1/RedHatText-Italic.woff
/usr/share/doc/libspelling-1/RedHatText-Italic.woff2
/usr/share/doc/libspelling-1/RedHatText-Medium.woff
/usr/share/doc/libspelling-1/RedHatText-Medium.woff2
/usr/share/doc/libspelling-1/RedHatText-MediumItalic.woff
/usr/share/doc/libspelling-1/RedHatText-MediumItalic.woff2
/usr/share/doc/libspelling-1/RedHatText-Regular.woff
/usr/share/doc/libspelling-1/RedHatText-Regular.woff2
/usr/share/doc/libspelling-1/SourceCodePro-It.ttf.woff
/usr/share/doc/libspelling-1/SourceCodePro-Regular.ttf.woff
/usr/share/doc/libspelling-1/SourceCodePro-Semibold.ttf.woff
/usr/share/doc/libspelling-1/Spelling.toml
/usr/share/doc/libspelling-1/class.Checker.html
/usr/share/doc/libspelling-1/class.Dictionary.html
/usr/share/doc/libspelling-1/class.Language.html
/usr/share/doc/libspelling-1/class.Provider.html
/usr/share/doc/libspelling-1/class.TextBufferAdapter.html
/usr/share/doc/libspelling-1/classes_hierarchy.html
/usr/share/doc/libspelling-1/ctor.Checker.new.html
/usr/share/doc/libspelling-1/ctor.TextBufferAdapter.new.html
/usr/share/doc/libspelling-1/fonts.css
/usr/share/doc/libspelling-1/func.DEPRECATED_FOR.html
/usr/share/doc/libspelling-1/func.DEPRECATED_IN_1_0_FOR.html
/usr/share/doc/libspelling-1/func.UNAVAILABLE.html
/usr/share/doc/libspelling-1/func.init.html
/usr/share/doc/libspelling-1/fzy.js
/usr/share/doc/libspelling-1/go-up-symbolic.png
/usr/share/doc/libspelling-1/index.html
/usr/share/doc/libspelling-1/index.json
/usr/share/doc/libspelling-1/libspelling-1.devhelp2
/usr/share/doc/libspelling-1/libspelling.svg
/usr/share/doc/libspelling-1/main.js
/usr/share/doc/libspelling-1/method.Checker.add_word.html
/usr/share/doc/libspelling-1/method.Checker.check_word.html
/usr/share/doc/libspelling-1/method.Checker.get_extra_word_chars.html
/usr/share/doc/libspelling-1/method.Checker.get_language.html
/usr/share/doc/libspelling-1/method.Checker.get_provider.html
/usr/share/doc/libspelling-1/method.Checker.ignore_word.html
/usr/share/doc/libspelling-1/method.Checker.list_corrections.html
/usr/share/doc/libspelling-1/method.Checker.set_language.html
/usr/share/doc/libspelling-1/method.Dictionary.add_word.html
/usr/share/doc/libspelling-1/method.Dictionary.contains_word.html
/usr/share/doc/libspelling-1/method.Dictionary.get_code.html
/usr/share/doc/libspelling-1/method.Dictionary.get_extra_word_chars.html
/usr/share/doc/libspelling-1/method.Dictionary.ignore_word.html
/usr/share/doc/libspelling-1/method.Dictionary.list_corrections.html
/usr/share/doc/libspelling-1/method.Language.get_code.html
/usr/share/doc/libspelling-1/method.Language.get_group.html
/usr/share/doc/libspelling-1/method.Language.get_name.html
/usr/share/doc/libspelling-1/method.Provider.get_default_code.html
/usr/share/doc/libspelling-1/method.Provider.get_display_name.html
/usr/share/doc/libspelling-1/method.Provider.list_languages.html
/usr/share/doc/libspelling-1/method.Provider.load_dictionary.html
/usr/share/doc/libspelling-1/method.Provider.supports_language.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.get_buffer.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.get_checker.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.get_enabled.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.get_language.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.get_menu_model.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.get_tag.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.invalidate_all.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.set_checker.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.set_enabled.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.set_language.html
/usr/share/doc/libspelling-1/method.TextBufferAdapter.update_corrections.html
/usr/share/doc/libspelling-1/opensearch.xml
/usr/share/doc/libspelling-1/overview.html
/usr/share/doc/libspelling-1/property.Checker.language.html
/usr/share/doc/libspelling-1/property.Checker.provider.html
/usr/share/doc/libspelling-1/property.Dictionary.code.html
/usr/share/doc/libspelling-1/property.Language.code.html
/usr/share/doc/libspelling-1/property.Language.group.html
/usr/share/doc/libspelling-1/property.Language.name.html
/usr/share/doc/libspelling-1/property.Provider.display-name.html
/usr/share/doc/libspelling-1/property.TextBufferAdapter.buffer.html
/usr/share/doc/libspelling-1/property.TextBufferAdapter.checker.html
/usr/share/doc/libspelling-1/property.TextBufferAdapter.enabled.html
/usr/share/doc/libspelling-1/property.TextBufferAdapter.language.html
/usr/share/doc/libspelling-1/search.js
/usr/share/doc/libspelling-1/solarized-dark.css
/usr/share/doc/libspelling-1/solarized-light.css
/usr/share/doc/libspelling-1/style.css
/usr/share/doc/libspelling-1/type_func.Checker.get_default.html
/usr/share/doc/libspelling-1/type_func.Provider.get_default.html
/usr/share/doc/libspelling-1/urlmap.js

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspelling-1.so.2
/usr/lib64/libspelling-1.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libspelling/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files locales -f libspelling.lang
%defattr(-,root,root,-)

